import type { Locale } from "@/lib/i18n";
import type { SiteCopy } from "@/content/types";

export { sectionSlugs } from "@/content/types";
export type { ContentBlock, Section, SectionSlug, SiteCopy } from "@/content/types";

const english: SiteCopy = {
  localeName: "العربية",
  nav: { about: "About COPAD", divisions: "Divisions", areas: "Therapy Areas", products: "Products", manufacturing: "Manufacturing & Quality", insights: "Insights", contact: "Contact Us" },
  utility: { allAreas: "Explore Therapy Areas", allDivisions: "View All Divisions", readProfile: "Read the Full Company Profile", next: "Next", submit: "Submit an Inquiry", formTitle: "How to Reach Us", formBody: "General inquiries, partnership requests, career applications, and product-related questions can each be submitted through the categories below. Medical professionals seeking product or safety information are directed to COPAD's dedicated medical information channel.", formLabels: ["Full name", "Work email", "Inquiry category", "Message"] },
  footer: { statement: "COPAD Pharma Egypt — Pharmaceuticals. Consumer Health. Manufacturing. Since 1989.", legal: "© 2026 COPAD Pharma Egypt. All rights reserved.", disclaimer: "Educational content is intended to inform and does not replace professional medical advice." },
  ui: {
    home: {
      heroImageAlt: "COPAD Pharma Egypt facility",
      sectionNavigationLabel: "Homepage sections",
      sectionNavigation: [
        { id: "home", label: "Home" },
        { id: "snapshot", label: "Snapshot" },
        { id: "introduction", label: "Company" },
        { id: "divisions", label: "Divisions" },
        { id: "therapy", label: "Therapy" },
        { id: "manufacturing", label: "Manufacturing" },
        { id: "connect", label: "Connect" },
      ],
      interactionLabels: { view: "VIEW", open: "OPEN", go: "GO" },
      introductionEyebrow: "Corporate Introduction",
      divisionsEyebrow: "Divisions Overview",
      divisionLabel: "Division",
      therapyEyebrow: "Therapy Areas Preview",
      therapyImageAlt: "COPAD pharmaceutical research and therapeutic expertise",
      therapyImageCaption: "A portfolio structured around clinical relevance",
      manufacturingEyebrow: "Manufacturing Preview",
      manufacturingAction: "View Manufacturing & Quality",
      manufacturingImageAlt: "COPAD manufacturing and quality facility",
      manufacturingImageEyebrow: "Integrated capability",
      manufacturingImageCaption: "Own manufacturing and toll manufacturing",
      manufacturingPrinciplesLabel: "Manufacturing principles",
      manufacturingPrinciples: ["Quality", "Regulatory alignment", "Operational discipline"],
      insightsEyebrow: "Insights Preview",
      insightsAction: "Visit Insights",
      partnershipEyebrow: "Partnership Preview",
      partnershipAction: "Partner With Us",
    },
    about: {
      heroFacts: [
        { label: "Established", value: "1989" },
        { label: "Headquarters", value: "Egypt" },
        { label: "Platform", value: "Integrated healthcare" },
      ],
      heroImageAlt: "COPAD Pharma Egypt corporate facility",
      heroCaption: "From healthcare representation to manufacturing and a multi-category healthcare platform.",
      heroSignature: "COPAD / 1989",
      historyEyebrow: "Corporate History",
      directionEyebrow: "Corporate Direction",
      directionDrivers: ["Consumer healthcare", "Contract manufacturing", "Cosmeceuticals"],
      directionImageAlt: "Pharmaceutical manufacturing facility",
      ambitionEyebrow: "National ambition",
      ambitionValue: "Top 20",
      ambitionBody: "Among Egypt's pharmaceutical companies by sales",
      distinctionEyebrow: "What Distinguishes COPAD",
      distinctionImageEyebrow: "Therapeutic depth",
      distinctionImageBody: "Clinical relevance built through specialization and sustainable growth",
      specialties: ["Central Nervous System", "Osteoarthritis", "Rheumatoid Arthritis"],
      valuesEyebrow: "Corporate Values",
      principles: ["Healthcare quality", "Regulatory integrity", "Long-term category development"],
      complianceEyebrow: "Compliance frameworks",
      regulators: ["Egyptian Drug Authority", "National Food Safety Authority", "Ministry of Health"],
    },
    footer: {
      navigationLabel: "Footer navigation",
      explore: "Explore",
      portfolio: "Portfolio",
      company: "Company",
      partnership: "Partner with us",
      careers: "Careers",
      socialLinks: [
        { label: "LinkedIn", shortLabel: "in", href: "https://www.linkedin.com/company/copad-egypt" },
        { label: "Facebook", shortLabel: "f", href: "https://www.facebook.com/copadegyptpharma/" },
      ],
    },
    formCategories: ["General Inquiries", "Partnership & Business Development", "Careers", "Product Inquiries", "Medical Information & Pharmacovigilance"],
    accessibility: {
      primaryNavigation: "Primary navigation",
      mobileNavigation: "Mobile navigation",
      openNavigation: "Open navigation",
      closeNavigation: "Close navigation",
      switchLanguage: "Switch language",
      mediaPlaceholder: "Media placeholder",
    },
  },
  home: {
    eyebrow: "Est. 1989", title: "COPAD Pharma Egypt", subheadline: "Advancing pharmaceuticals, consumer health, and manufacturing across Egypt and beyond.",
    body: "COPAD Pharma Egypt is a diversified healthcare company operating across pharmaceuticals, consumer health, nutrition, and veterinary products. Built on a foundation of manufacturing capability and therapeutic depth, the company serves healthcare professionals, distributors, and consumers through a portfolio spanning multiple therapeutic areas and wellness categories.", primaryCta: "Explore the Company", secondaryCta: "View Therapy Areas",
    snapshot: ["Established 1989", "Multiple therapeutic areas", "Own manufacturing and toll manufacturing", "Consumer health and nutrition portfolio", "Target: Top 20 pharmaceutical company in Egypt"],
    introduction: { title: "A Healthcare Platform Built for Scale", body: "Since its establishment, COPAD has evolved from healthcare representation and import activity into a full-scale operation spanning pharmaceutical manufacturing, product development, and consumer-health commercialization. The company's structure reflects a deliberate progression: from introducing global healthcare products into the Egyptian market, to building domestic manufacturing capability, to developing a broad and diversified product portfolio serving both clinical and consumer needs.", note: "Today, COPAD's operations are organized around therapeutic specialization, manufacturing reliability, and category expansion — a structure designed to support continued growth across the Egyptian and regional healthcare markets." },
    divisions: { title: "Four Divisions, One Corporate Structure", body: "COPAD operates across four core divisions: Pharmaceuticals, Consumer Health, Veterinary Products, and Manufacturing & Partnerships. Each division addresses a distinct market need while operating within a unified corporate identity built on quality, consistency, and healthcare relevance.", items: ["Pharmaceuticals — The clinical foundation of the business, spanning multiple therapeutic areas including CNS, cardiometabolic health, orthopedics, and rheumatology.", "Consumer Health — Vitamins, supplements, and wellness products developed for everyday relevance across immunity, nutrition, and family health.", "Veterinary — Animal-health products extending COPAD's manufacturing and product-development capability beyond human healthcare.", "Manufacturing & Partnerships — Own manufacturing and toll manufacturing capacity supporting long-term commercial partnerships and regional expansion."] },
    therapy: { title: "A Portfolio Organized by Therapeutic Expertise", body: "COPAD's pharmaceutical portfolio is structured across nine therapeutic areas: Central Nervous System, Orthopedics, Rheumatology, Cardiometabolic Diseases, Gynecology and Andrology, Gastrointestinal Health, Ear-Nose-Throat, Pulmonology, and Immunology. This structure allows the company's clinical expertise to be understood by medical relevance rather than by product name alone." },
    manufacturing: { title: "Manufacturing Capability at the Core", body: "COPAD's operations are supported by domestic manufacturing facilities and toll-manufacturing capacity, positioning the company as both a product developer and a manufacturing partner within the Egyptian pharmaceutical sector. Manufacturing quality, regulatory alignment, and operational discipline underpin every stage of production." },
    insights: { title: "Healthcare Knowledge, Shared Responsibly", body: "COPAD publishes educational content addressing disease awareness, nutritional guidance, and healthcare developments relevant to its therapeutic areas. Content is developed to inform rather than promote, in line with healthcare communication standards in Egypt." },
    partnership: { title: "Built for Long-Term Partnership", body: "COPAD works with distributors, export partners, and manufacturing collaborators across Egypt and the wider region. The company's growing manufacturing base and expanding product portfolio create a strong foundation for new commercial partnerships." },
  },
  sections: {
    about: { eyebrow: "About COPAD", title: "About COPAD", intro: "COPAD Pharma Egypt is an Egyptian healthcare company with operations spanning pharmaceuticals, consumer health, veterinary products, and manufacturing. Established in 1989, the company has grown from a healthcare representation and import business into a diversified operation with its own manufacturing capability, a broad product portfolio, and an expanding presence across multiple therapeutic and consumer-health categories.", cta: "View Manufacturing & Quality", blocks: [
      { title: "From Representation to Manufacturing", body: "COPAD's early activity centered on representing global healthcare companies and introducing their products to the Egyptian market. This period established the company's foundational relationships and healthcare-market expertise. Over time, COPAD transitioned into direct manufacturing, building both owned production capability and toll-manufacturing services for partner brands. This shift from representation to manufacturing marked a defining stage in the company's development, enabling greater control over quality, scale, and product diversification.", items: ["1989 — COPAD is established in Egypt.", "Early years — Representation of international healthcare companies and import-driven market entry.", "Growth phase — Transition into own manufacturing and toll manufacturing.", "Portfolio expansion — Development of a multi-category product range spanning pharmaceuticals, supplements, and nutrition.", "Current phase — Corporate transformation focused on brand consolidation, manufacturing credibility, and consumer-health growth."] },
      { title: "A Company in Active Growth", body: "COPAD's stated ambition is to advance from its current market position into Egypt's top 20 pharmaceutical companies by sales, supported by expansion across consumer healthcare, contract manufacturing, and cosmeceuticals. This growth strategy reflects a broader shift in the company's identity — from a therapeutic-area specialist to a diversified healthcare platform serving clinical, consumer, and institutional audiences." },
      { title: "Specialization and Sustainability", body: "COPAD identifies specialization and sustainability as its core differentiators within the Egyptian pharmaceutical sector. The company's therapeutic depth is most pronounced in Central Nervous System products and joint-related categories, including osteoarthritis and rheumatoid arthritis, where COPAD has built a strong position of clinical relevance. This specialization is paired with a long-term approach to category growth, positioning the company for sustained expansion rather than short-term category entry." },
      { title: "The Principles Behind the Portfolio", body: "COPAD's operations are guided by a commitment to healthcare quality, regulatory integrity, and long-term category development. Every stage of the company's activity — from manufacturing to product development to public communication — operates within the compliance frameworks set by the Egyptian Drug Authority, the National Food Safety Authority, and the Ministry of Health." },
    ] },
    divisions: { eyebrow: "Divisions", title: "Divisions", intro: "COPAD's operating structure spans four divisions — Pharmaceuticals, Consumer Health, Veterinary, and Manufacturing & Partnerships. Each division serves a distinct audience and market function, while operating under a single corporate identity built on healthcare credibility and long-term growth.", blocks: [
      { title: "Pharmaceuticals", body: "The pharmaceutical division represents COPAD's clinical foundation. It comprises products developed and organized across multiple therapeutic areas, addressing conditions ranging from neurological and psychiatric health to cardiometabolic disease, joint and inflammatory conditions, and gastrointestinal health. This division is directed primarily toward healthcare professionals, pharmacists, and distributors, and operates under the regulatory frameworks governing prescription medicine in Egypt." },
      { title: "Consumer Health", body: "COPAD's consumer-health division includes vitamins, supplements, and wellness-oriented products developed for daily relevance across immunity, nutrition, energy, and family health. This division represents the company's primary growth direction, designed to reach consumers directly through retail, pharmacy, and future e-commerce channels." },
      { title: "Veterinary", body: "COPAD's veterinary division extends the company's manufacturing and product-development expertise into animal health, supporting a product range developed alongside its human-healthcare portfolio. This division reflects the company's broader healthcare mandate beyond human medicine." },
      { title: "Manufacturing & Partnerships", body: "Beyond its branded portfolio, COPAD provides manufacturing and toll-manufacturing services to partner companies, leveraging its production capability to support third-party brands. This division underpins the company's institutional credibility and forms the basis for future contract-manufacturing and export partnerships." },
    ] },
    "therapeutic-areas": { eyebrow: "Therapy Areas", title: "Therapy Areas", intro: "COPAD's pharmaceutical portfolio is organized across nine therapeutic areas, each representing a distinct field of medical specialization. This structure reflects standard pharmaceutical classification practice, grouping products by the body system or condition they address rather than by product name alone.", cta: "Contact Medical Information", blocks: [
      { title: "Central Nervous System (CNS)", body: "The Central Nervous System comprises the brain, spinal cord, and nerve pathways governing cognition, mood, behavior, and neurological function. Conditions within this field include psychiatric disorders, memory and cognitive concerns, sleep disturbance, and nerve-related dysfunction. CNS represents one of COPAD's most established therapeutic areas, reflecting a significant share of the company's clinical portfolio and market presence." },
      { title: "Orthopedics", body: "Orthopedics addresses the health of bones, joints, muscles, and connective structures that support the body's movement and stability. This field includes conditions related to bone density, joint function, and musculoskeletal support, and connects closely with COPAD's broader joint-health and mobility-related product range." },
      { title: "Rheumatology", body: "Rheumatology covers inflammatory and autoimmune conditions affecting joints, muscles, and connective tissue, most notably rheumatoid arthritis. Distinct from the mechanical joint wear addressed in orthopedic care, rheumatological conditions involve the body's immune response. COPAD maintains a strong position across both osteoarthritis and rheumatoid arthritis, two of the company's most established areas of clinical recognition." },
      { title: "Cardiometabolic Diseases (CMD)", body: "Cardiometabolic Diseases encompass the interconnected health of the heart, blood vessels, and metabolic system, including hypertension, diabetes, cholesterol regulation, and weight-related health risk. Given the scale of cardiometabolic conditions across the Egyptian population, this therapeutic area represents one of COPAD's largest and most clinically significant portfolios." },
      { title: "Gynecology and Andrology", body: "Gynecology addresses women's reproductive and hormonal health, while Andrology addresses the equivalent field for men. Together, these areas form a therapeutic category requiring particular clinical precision and communication discretion, reflecting both the medical sensitivity of the conditions involved and cultural considerations relevant to public health communication." },
      { title: "Gastrointestinal Health", body: "Gastrointestinal health covers the function of the stomach and digestive system, including conditions related to digestion, acid balance, and intestinal health. As one of the most common categories of everyday healthcare need, gastrointestinal products serve a broad segment of both clinical and pharmacy-counter demand." },
      { title: "Ear, Nose, and Throat (ENT)", body: "ENT addresses conditions affecting the upper respiratory passages, throat, and ear function. This therapeutic area supports a category of healthcare need that is closely tied to seasonal patterns and everyday clinical demand across the Egyptian market." },
      { title: "Pulmonology", body: "Pulmonology is concerned with the health of the lungs and respiratory system, including chronic and acute respiratory conditions. This field represents a growing area of relevance within COPAD's expanding therapeutic scope." },
      { title: "Immunology", body: "Immunology addresses the function of the immune system, including its role in inflammation, allergic response, and overall health resilience. This therapeutic area bridges COPAD's clinical portfolio with its broader consumer-health category, particularly through immune-support formulations." },
    ] },
    products: { eyebrow: "Products", title: "Products", intro: "COPAD's product portfolio spans pharmaceutical treatments, supplements, nutrition products, and wellness formulations. Presentation of each category reflects its regulatory classification: pharmaceutical products are presented for informational reference in line with healthcare-communication standards, while consumer-health products are presented with full commercial detail.", cta: "Contact Medical Information", blocks: [
      { title: "Pharmaceutical Portfolio", body: "COPAD's pharmaceutical products are developed across nine therapeutic areas and are intended for use under medical guidance. In accordance with healthcare-communication standards governing prescription medicine in Egypt, pharmaceutical products are presented here by therapeutic classification rather than individual promotional detail. Healthcare professionals seeking further product information are directed to COPAD's professional resources.", note: "List by therapy area; product name and dosage form only; no product imagery; optional professional-access gateway for HCPs." },
      { title: "Supplements, Vitamins, and Wellness", body: "COPAD's consumer-health portfolio includes a wide range of vitamins, minerals, and wellness formulations developed to support everyday health needs. Categories include immune support, nutritional supplementation, joint and mobility support, cognitive wellness, and family health. These products are developed for direct consumer relevance and are presented with full product detail.", items: ["Immunity Support", "Omega & Essential Nutrients", "Joint & Mobility Support", "Men's Wellness", "Women's Wellness", "Prenatal & Maternal Support", "Kids' Nutrition", "Cognitive & Nerve Support", "Vitamins & Minerals", "Digestive Support"] },
      { title: "Centravita", body: "Centravita is COPAD's dedicated range of vitamins, minerals, and wellness formulations, spanning one of the broadest product lines within the company's consumer-health portfolio. The range addresses a wide spectrum of everyday health needs, from cognitive and nerve support to men's and women's wellness, prenatal nutrition, and general vitamin supplementation.", items: ["Brain & Cognitive Support", "Men's Wellness", "Women's Wellness", "Prenatal & Maternal Support", "Immunity & Vitamin Support", "Joint & Mobility Support", "General Nutrition"] },
      { title: "Pediatric and Family Health", body: "COPAD's pediatric and family-health products are formulated to support children's nutrition and everyday family wellness needs. This category reflects the company's broader commitment to healthcare relevance across all life stages." },
    ] },
    "manufacturing-quality": { eyebrow: "Manufacturing & Quality", title: "Manufacturing & Quality", intro: "COPAD's manufacturing operations form the foundation of its pharmaceutical and consumer-health portfolio. Combining owned production facilities with toll-manufacturing capability, the company has built a manufacturing base designed to support both its branded products and third-party commercial partnerships.", cta: "Contact Regulatory Affairs", blocks: [
      { title: "Manufacturing Built for Growth", body: "COPAD's manufacturing operations support the company's expanding product portfolio across pharmaceuticals, supplements, and nutrition. Alongside its own production lines, COPAD provides toll-manufacturing services, enabling partner companies to leverage the company's production capacity and technical expertise. This dual capability positions COPAD as both a product owner and a manufacturing partner within Egypt's healthcare-manufacturing sector." },
      { title: "Quality as an Operating Standard", body: "Manufacturing within the pharmaceutical and consumer-health sectors requires rigorous quality systems, documentation control, and category-specific regulatory discipline. COPAD's production processes are structured to meet these requirements consistently across every product category, from prescription pharmaceuticals to consumer supplements." },
      { title: "Operating Within a Regulated Framework", body: "COPAD's manufacturing, product development, and public communication operate within the regulatory frameworks established by the Egyptian Drug Authority, the National Food Safety Authority, and the Ministry of Health. Compliance with these frameworks governs every stage of the company's operations, from production standards to permissible public communication for each product category." },
    ] },
    insights: { eyebrow: "Insights", title: "Insights", intro: "COPAD publishes educational content addressing disease awareness, nutritional guidance, and healthcare developments relevant to its therapeutic areas. Content is developed for public understanding and healthcare education, distinct from promotional or product-specific communication.", cta: "View All Insights", blocks: [
      { title: "Disease Awareness", body: "This section addresses the medical fundamentals behind COPAD's therapeutic areas — explaining conditions, their general management, and their relevance to public health, without reference to specific prescription products.", items: ["Understanding Rheumatoid Arthritis", "The Basics of Cardiometabolic Health", "Digestive Health: Common Concerns Explained", "Recognizing Respiratory Health Issues"] },
      { title: "Nutrition & Wellness", body: "This section addresses nutritional and supplement-related topics relevant to COPAD's consumer-health portfolio, providing general health education around vitamins, minerals, and everyday wellness support.", items: ["The Role of Omega Fatty Acids in Daily Health", "Iron and Nutritional Balance", "Supporting Immunity Through Nutrition", "Prenatal Nutrition: What Matters Most"] },
      { title: "Corporate & Industry", body: "This section covers COPAD's corporate developments, manufacturing milestones, and broader context within the Egyptian pharmaceutical industry.", items: ["Manufacturing Quality in the Egyptian Pharmaceutical Sector", "Understanding Therapeutic Area Specialization", "How Pharmaceutical and Consumer-Health Portfolios Differ"] },
    ] },
    "partner-with-us": { eyebrow: "Partner With Us", title: "Partner With Us", intro: "COPAD's manufacturing capability, therapeutic breadth, and consumer-health growth create a foundation for structured commercial partnerships across distribution, export, and contract manufacturing. The company welcomes collaboration with distributors, export partners, and manufacturing clients across Egypt and the broader region.", cta: "Submit a Partnership Inquiry", blocks: [
      { title: "Distribution Partnerships", body: "COPAD works with pharmacy and healthcare distribution partners across Egypt to ensure consistent access to its pharmaceutical and consumer-health portfolio. Distribution partnerships are structured to support reliable supply, consistent pricing, and long-term commercial alignment." },
      { title: "Export Collaboration", body: "COPAD's manufacturing capacity and expanding product portfolio support export opportunities across regional markets. The company is open to discussions with export partners seeking access to its pharmaceutical and consumer-health product lines." },
      { title: "Contract & Toll Manufacturing", body: "COPAD provides toll-manufacturing services to partner companies, offering access to its production capability, technical expertise, and quality systems. This service supports partner brands seeking reliable manufacturing capacity within the Egyptian market." },
    ] },
    careers: { eyebrow: "Careers", title: "Careers", intro: "COPAD's growth across pharmaceutical, consumer-health, and manufacturing operations requires a multidisciplinary workforce spanning scientific, operational, commercial, and corporate functions. The company's expansion strategy creates ongoing opportunities across multiple departments and career levels.", cta: "Submit Your CV", blocks: [
      { title: "Working at COPAD", body: "COPAD's teams span manufacturing, quality assurance, regulatory affairs, commercial operations, and corporate functions. As the company expands its consumer-health and manufacturing divisions, opportunities continue to grow across both established and emerging areas of the business." },
      { title: "Current Opportunities", body: "Available positions are listed below. Interested candidates are invited to submit their applications for review by COPAD's recruitment team." },
    ] },
    contact: { eyebrow: "Contact Us", title: "Contact Us", intro: "Corporate, commercial, and product-related inquiries can be directed through COPAD's central contact channels. Inquiries are routed to the appropriate department for timely response.", cta: "Submit an Inquiry", blocks: [
      { title: "How to Reach Us", body: "General inquiries, partnership requests, career applications, and product-related questions can each be submitted through the categories below. Medical professionals seeking product or safety information are directed to COPAD's dedicated medical information channel.", items: ["General Inquiries", "Partnership & Business Development", "Careers", "Product Inquiries", "Medical Information & Pharmacovigilance"] },
      { title: "Corporate Office", body: "COPAD Pharma Egypt maintains its corporate offices and manufacturing operations within Egypt, supporting both its domestic commercial activity and its regional partnership network." },
    ] },
  },
};

const arabic: SiteCopy = {
  ...english,
  localeName: "English",
  nav: { about: "عن كوباد", divisions: "القطاعات", areas: "المجالات العلاجية", products: "المنتجات", manufacturing: "التصنيع والجودة", insights: "المعرفة والأخبار", contact: "تواصل معنا" },
  utility: { ...english.utility, allAreas: "استكشف المجالات العلاجية", allDivisions: "كل القطاعات", readProfile: "اقرأ الملف التعريفي الكامل", next: "التالي", submit: "أرسل الاستفسار", formTitle: "طرق التواصل", formBody: "يمكن إرسال الاستفسارات العامة وطلبات الشراكات وطلبات التوظيف والاستفسارات المتعلقة بالمنتجات من خلال التصنيفات التالية. ويوجّه المختصون في الرعاية الصحية إلى قناة المعلومات الطبية المخصصة.", formLabels: ["الاسم الكامل", "البريد الإلكتروني للعمل", "نوع الاستفسار", "الرسالة"] },
  footer: { statement: "كوباد فارما مصر — أدوية. صحة المستهلك. تصنيع. منذ 1989.", legal: "© 2026 كوباد فارما مصر. جميع الحقوق محفوظة.", disclaimer: "المحتوى التثقيفي يهدف إلى المعرفة ولا يغني عن استشارة المختصين." },
  ui: {
    home: {
      heroImageAlt: "منشأة كوباد فارما مصر",
      sectionNavigationLabel: "أقسام الصفحة الرئيسية",
      sectionNavigation: [
        { id: "home", label: "الرئيسية" },
        { id: "snapshot", label: "لمحة" },
        { id: "introduction", label: "عن كوباد" },
        { id: "divisions", label: "القطاعات" },
        { id: "therapy", label: "المجالات العلاجية" },
        { id: "manufacturing", label: "التصنيع" },
        { id: "connect", label: "تواصل" },
      ],
      interactionLabels: { view: "شاهد", open: "افتح", go: "اذهب" },
      introductionEyebrow: "مقدمة مؤسسية",
      divisionsEyebrow: "نظرة عامة على القطاعات",
      divisionLabel: "القطاع",
      therapyEyebrow: "نظرة على المجالات العلاجية",
      therapyImageAlt: "البحث والتخصصات العلاجية في كوباد",
      therapyImageCaption: "محفظة منظمة وفق الأهمية الإكلينيكية",
      manufacturingEyebrow: "نظرة على التصنيع",
      manufacturingAction: "استكشف التصنيع والجودة",
      manufacturingImageAlt: "منشأة كوباد للتصنيع والجودة",
      manufacturingImageEyebrow: "قدرة متكاملة",
      manufacturingImageCaption: "تصنيع مملوك وتصنيع للغير",
      manufacturingPrinciplesLabel: "مبادئ التصنيع",
      manufacturingPrinciples: ["الجودة", "التوافق التنظيمي", "الانضباط التشغيلي"],
      insightsEyebrow: "نظرة على المعرفة والأخبار",
      insightsAction: "زيارة المعرفة والأخبار",
      partnershipEyebrow: "نظرة على الشراكات",
      partnershipAction: "كن شريكًا لنا",
    },
    about: {
      heroFacts: [
        { label: "تأسست", value: "1989" },
        { label: "المقر الرئيسي", value: "مصر" },
        { label: "المنصة", value: "رعاية صحية متكاملة" },
      ],
      heroImageAlt: "المقر المؤسسي لكوباد فارما مصر",
      heroCaption: "من تمثيل شركات الرعاية الصحية إلى التصنيع ومنصة رعاية صحية متعددة الفئات.",
      heroSignature: "COPAD / 1989",
      historyEyebrow: "التاريخ المؤسسي",
      directionEyebrow: "الاتجاه المؤسسي",
      directionDrivers: ["صحة المستهلك", "التصنيع التعاقدي", "مستحضرات التجميل العلاجية"],
      directionImageAlt: "منشأة للتصنيع الدوائي",
      ambitionEyebrow: "الطموح الوطني",
      ambitionValue: "ضمن أكبر 20 شركة",
      ambitionBody: "بين شركات الأدوية في مصر حسب المبيعات",
      distinctionEyebrow: "ما يميز كوباد",
      distinctionImageEyebrow: "عمق علاجي",
      distinctionImageBody: "خبرة سريرية مبنية على التخصص والنمو المستدام",
      specialties: ["الجهاز العصبي المركزي", "خشونة المفاصل", "التهاب المفاصل الروماتويدي"],
      valuesEyebrow: "القيم المؤسسية",
      principles: ["جودة الرعاية الصحية", "النزاهة التنظيمية", "تطوير الفئات طويل الأمد"],
      complianceEyebrow: "أطر الامتثال",
      regulators: ["هيئة الدواء المصرية", "الهيئة القومية لسلامة الغذاء", "وزارة الصحة"],
    },
    footer: {
      navigationLabel: "روابط تذييل الموقع",
      explore: "استكشف",
      portfolio: "المحفظة",
      company: "الشركة",
      partnership: "الشراكة معنا",
      careers: "الوظائف",
      socialLinks: [
        { label: "لينكدإن", shortLabel: "in", href: "https://www.linkedin.com/company/copad-egypt" },
        { label: "فيسبوك", shortLabel: "f", href: "https://www.facebook.com/copadegyptpharma/" },
      ],
    },
    formCategories: ["استفسارات عامة", "الشراكات وتطوير الأعمال", "الوظائف", "استفسارات المنتجات", "المعلومات الطبية واليقظة الدوائية"],
    accessibility: {
      primaryNavigation: "التنقل الرئيسي",
      mobileNavigation: "التنقل عبر الهاتف",
      openNavigation: "فتح قائمة التنقل",
      closeNavigation: "إغلاق قائمة التنقل",
      switchLanguage: "تغيير اللغة",
      mediaPlaceholder: "عنصر وسائط مؤقت",
    },
  },
  home: {
    ...english.home,
    eyebrow: "تأسست عام 1989",
    title: "كوباد فارما مصر",
    subheadline: "نرتقي بالأدوية وصحة المستهلك والتصنيع في مصر وخارجها.",
    body: "كوباد فارما مصر شركة رعاية صحية متنوعة تعمل في مجالات الأدوية وصحة المستهلك والتغذية والمنتجات البيطرية. وانطلاقًا من قاعدة راسخة من القدرات التصنيعية والعمق العلاجي، تخدم الشركة المتخصصين في الرعاية الصحية والموزعين والمستهلكين من خلال محفظة تمتد عبر مجالات علاجية متعددة وفئات متنوعة للصحة والعافية.",
    primaryCta: "استكشف الشركة",
    secondaryCta: "استعرض المجالات العلاجية",
    snapshot: ["تأسست عام 1989", "مجالات علاجية متعددة", "تصنيع مملوك وتصنيع للغير", "محفظة لصحة المستهلك والتغذية", "الهدف: أن تصبح ضمن أكبر 20 شركة أدوية في مصر"],
    introduction: {
      title: "منصة رعاية صحية مبنية للنمو",
      body: "منذ تأسيسها، تطورت كوباد من نشاط لتمثيل شركات الرعاية الصحية والاستيراد إلى منظومة متكاملة تمتد عبر التصنيع الدوائي وتطوير المنتجات وتسويق منتجات صحة المستهلك. ويعكس هيكل الشركة مسارًا مدروسًا بدأ بتقديم منتجات الرعاية الصحية العالمية إلى السوق المصري، ثم بناء قدرات التصنيع المحلية، وصولًا إلى تطوير محفظة واسعة ومتنوعة من المنتجات تخدم الاحتياجات الإكلينيكية واحتياجات المستهلكين على حد سواء.",
      note: "تُنظّم عمليات كوباد اليوم حول التخصص العلاجي وموثوقية التصنيع والتوسع في الفئات — ضمن هيكل صُمم لدعم النمو المستمر في أسواق الرعاية الصحية المصرية والإقليمية.",
    },
    divisions: {
      title: "أربعة قطاعات ضمن هيكل مؤسسي واحد",
      body: "تعمل كوباد عبر أربعة قطاعات رئيسية: الأدوية، وصحة المستهلك، والمنتجات البيطرية، والتصنيع والشراكات. ويلبي كل قطاع احتياجًا مختلفًا في السوق، بينما تعمل جميع القطاعات ضمن هوية مؤسسية موحدة تقوم على الجودة والاتساق والارتباط باحتياجات الرعاية الصحية.",
      items: [
        "الأدوية — الأساس الإكلينيكي للأعمال، ويمتد عبر مجالات علاجية متعددة تشمل الجهاز العصبي المركزي وصحة القلب والتمثيل الغذائي والعظام والروماتيزم.",
        "صحة المستهلك — فيتامينات ومكملات ومنتجات للعافية طُورت لتلائم الاحتياجات اليومية في مجالات المناعة والتغذية وصحة الأسرة.",
        "المنتجات البيطرية — منتجات لصحة الحيوان توسّع قدرات كوباد في التصنيع وتطوير المنتجات إلى ما يتجاوز الرعاية الصحية البشرية.",
        "التصنيع والشراكات — قدرات للتصنيع المملوك والتصنيع للغير تدعم الشراكات التجارية طويلة الأجل والتوسع الإقليمي.",
      ],
    },
    therapy: {
      title: "محفظة منظمة وفق الخبرة العلاجية",
      body: "تُنظّم محفظة كوباد الدوائية عبر تسعة مجالات علاجية: الجهاز العصبي المركزي، والعظام، والروماتيزم، وأمراض القلب والتمثيل الغذائي، والنساء والذكورة، وصحة الجهاز الهضمي، والأنف والأذن والحنجرة، وأمراض الصدر، والمناعة. ويتيح هذا الهيكل فهم خبرة الشركة الإكلينيكية وفق أهميتها الطبية بدلًا من الاقتصار على أسماء المنتجات.",
    },
    manufacturing: {
      title: "القدرة التصنيعية في صميم الأعمال",
      body: "تستند عمليات كوباد إلى منشآت تصنيع محلية وقدرات للتصنيع للغير، ما يضع الشركة في موقع يجمع بين تطوير المنتجات والعمل كشريك تصنيع داخل قطاع الدواء المصري. وتدعم جودة التصنيع والمواءمة التنظيمية والانضباط التشغيلي كل مرحلة من مراحل الإنتاج.",
    },
    insights: {
      title: "معرفة صحية تُشارك بمسؤولية",
      body: "تنشر كوباد محتوى تثقيفيًا يتناول الوعي بالأمراض والإرشاد الغذائي وتطورات الرعاية الصحية المرتبطة بمجالاتها العلاجية. ويُعد المحتوى بهدف التوعية لا الترويج، بما يتوافق مع معايير التواصل في مجال الرعاية الصحية في مصر.",
    },
    partnership: {
      title: "شراكات مبنية للاستمرار",
      body: "تعمل كوباد مع الموزعين وشركاء التصدير وشركاء التصنيع في مصر والمنطقة الأوسع. وتوفر القاعدة التصنيعية المتنامية للشركة ومحفظة منتجاتها الآخذة في التوسع أساسًا قويًا لشراكات تجارية جديدة.",
    },
  },
  sections: {
    about: { ...english.sections.about, eyebrow: "عن كوباد", title: "عن كوباد", intro: "كوباد فارما مصر شركة رعاية صحية مصرية تمتد عملياتها عبر الأدوية وصحة المستهلك والمنتجات البيطرية والتصنيع. ومنذ تأسيسها عام 1989، تطورت الشركة من نشاط لتمثيل شركات الرعاية الصحية والاستيراد إلى منظومة متنوعة تمتلك قدراتها التصنيعية الخاصة، ومحفظة واسعة من المنتجات، وحضورًا متناميًا عبر مجالات علاجية وفئات متعددة لصحة المستهلك.", cta: "عرض التصنيع والجودة", blocks: [
      { title: "من التمثيل إلى التصنيع", body: "تمحور نشاط كوباد في بداياته حول تمثيل شركات الرعاية الصحية العالمية وتقديم منتجاتها إلى السوق المصري. وأسست هذه المرحلة علاقات الشركة الرئيسية وخبرتها في سوق الرعاية الصحية. ومع مرور الوقت، انتقلت كوباد إلى التصنيع المباشر، فبنت قدرات إنتاجية مملوكة وخدمات للتصنيع للغير لصالح العلامات التجارية الشريكة. وقد شكّل هذا التحول من التمثيل إلى التصنيع مرحلة حاسمة في تطور الشركة، إذ أتاح لها تحكمًا أكبر في الجودة وحجم الإنتاج وتنويع المنتجات.", items: ["1989 — تأسست كوباد في مصر.", "السنوات الأولى — تمثيل شركات الرعاية الصحية الدولية ودخول السوق بالاعتماد على الاستيراد.", "مرحلة النمو — الانتقال إلى التصنيع المملوك والتصنيع للغير.", "توسع المحفظة — تطوير مجموعة منتجات متعددة الفئات تشمل الأدوية والمكملات ومنتجات التغذية.", "المرحلة الحالية — تحول مؤسسي يركز على توحيد العلامة التجارية وترسيخ مصداقية التصنيع وتنمية قطاع صحة المستهلك."] },
      { title: "شركة في مرحلة نمو نشطة", body: "تتمثل طموحات كوباد المعلنة في الانتقال من موقعها الحالي في السوق إلى قائمة أكبر 20 شركة أدوية في مصر من حيث المبيعات، مدعومة بالتوسع في صحة المستهلك والتصنيع التعاقدي ومستحضرات التجميل ذات الطابع العلاجي. وتعكس استراتيجية النمو هذه تحولًا أوسع في هوية الشركة — من شركة متخصصة في مجالات علاجية إلى منصة رعاية صحية متنوعة تخدم الجمهور الإكلينيكي والمستهلكين والمؤسسات." },
      { title: "التخصص والاستدامة", body: "تعتبر كوباد التخصص والاستدامة عاملَي التميز الأساسيين لها داخل قطاع الدواء المصري. ويظهر العمق العلاجي للشركة بصورة أوضح في منتجات الجهاز العصبي المركزي والفئات المرتبطة بالمفاصل، بما فيها خشونة المفاصل والتهاب المفاصل الروماتويدي، حيث بنت كوباد مكانة قوية ذات أهمية إكلينيكية. ويقترن هذا التخصص بنهج طويل الأجل لتنمية الفئات، بما يهيئ الشركة لتوسع مستدام بدلًا من الدخول قصير الأجل إلى الفئات." },
      { title: "المبادئ التي تقف خلف المحفظة", body: "تسترشد عمليات كوباد بالتزامها بجودة الرعاية الصحية والنزاهة التنظيمية وتنمية الفئات على المدى الطويل. وتعمل كل مرحلة من مراحل نشاط الشركة — من التصنيع إلى تطوير المنتجات والتواصل العام — ضمن أطر الامتثال التي تحددها هيئة الدواء المصرية والهيئة القومية لسلامة الغذاء ووزارة الصحة." },
    ] },
    divisions: { ...english.sections.divisions, eyebrow: "القطاعات", title: "القطاعات", intro: "يمتد هيكل كوباد التشغيلي عبر أربعة قطاعات: الأدوية، وصحة المستهلك، والبيطري، والتصنيع والشراكات. ويخدم كل قطاع جمهورًا ووظيفة سوقية مختلفة ضمن هوية مؤسسية واحدة.", blocks: [
      { title: "الأدوية", body: "يمثل قطاع الأدوية الأساس الإكلينيكي لكوباد، ويضم منتجات منظمة عبر مجالات علاجية متعددة تشمل الصحة العصبية والنفسية وأمراض القلب والتمثيل الغذائي وصحة المفاصل والجهاز الهضمي." },
      { title: "صحة المستهلك", body: "يضم القطاع فيتامينات ومكملات ومنتجات عافية للاستخدام اليومي عبر المناعة والتغذية والطاقة وصحة الأسرة، وهو اتجاه النمو الرئيسي للشركة." },
      { title: "البيطري", body: "يمتد القطاع البيطري بخبرات كوباد في التصنيع وتطوير المنتجات إلى صحة الحيوان، إلى جانب محفظة الرعاية الصحية البشرية." },
      { title: "التصنيع والشراكات", body: "تقدم كوباد خدمات التصنيع والتصنيع للغير للشركات الشريكة، بما يدعم العلامات الخارجية ويؤسس للشراكات التصنيعية والتصديرية القادمة." },
    ] },
    "therapeutic-areas": { ...english.sections["therapeutic-areas"], eyebrow: "المجالات العلاجية", title: "المجالات العلاجية", intro: "تنظم محفظة كوباد الدوائية عبر تسعة مجالات علاجية، بحيث يمثل كل منها مجالًا طبيًا متخصصًا وفق تصنيف دوائي قياسي يعتمد على الجهاز أو الحالة الصحية.", cta: "تواصل مع المعلومات الطبية", blocks: [
      { title: "الجهاز العصبي المركزي", body: "يشمل الدماغ والحبل الشوكي والمسارات العصبية المرتبطة بالإدراك والمزاج والسلوك والوظائف العصبية. ويُعد من أكثر مجالات كوباد العلاجية رسوخًا." },
      { title: "العظام", body: "يهتم بصحة العظام والمفاصل والعضلات والأنسجة الداعمة للحركة والثبات، ويتصل بمحفظة كوباد لصحة المفاصل والحركة." },
      { title: "الروماتيزم", body: "يغطي الحالات الالتهابية والمناعية المؤثرة في المفاصل والعضلات والأنسجة، وفي مقدمتها التهاب المفاصل الروماتويدي، إلى جانب خشونة المفاصل." },
      { title: "أمراض القلب والتمثيل الغذائي", body: "يشمل الترابط بين صحة القلب والأوعية والتمثيل الغذائي، بما فيه ضغط الدم والسكري والكوليسترول ومخاطر الوزن." },
      { title: "النساء والذكورة", body: "يعالج الصحة الإنجابية والهرمونية للنساء والرجال بدقة إكلينيكية وحساسية تواصلية تراعي طبيعة هذه الحالات." },
      { title: "صحة الجهاز الهضمي", body: "يغطي المعدة والجهاز الهضمي وموضوعات الهضم وتوازن الحموضة وصحة الأمعاء، وهي من أكثر احتياجات الرعاية الصحية شيوعًا." },
      { title: "الأنف والأذن والحنجرة", body: "يعالج الحالات المرتبطة بالممرات التنفسية العليا والحلق ووظائف الأذن، ذات الصلة بالاحتياجات الموسمية والطلب الإكلينيكي اليومي." },
      { title: "أمراض الصدر", body: "يهتم بصحة الرئتين والجهاز التنفسي، بما يشمل الحالات التنفسية المزمنة والحادة." },
      { title: "المناعة", body: "يتناول وظائف جهاز المناعة ودوره في الالتهاب والحساسية والقدرة الصحية العامة، ويربط بين المحفظة الإكلينيكية وصحة المستهلك." },
    ] },
    products: { ...english.sections.products, eyebrow: "المنتجات", title: "المنتجات", intro: "تمتد محفظة كوباد بين العلاجات الدوائية والمكملات ومنتجات التغذية والعافية. ويعكس تقديم كل فئة تصنيفها التنظيمي ومعايير التواصل الصحي في مصر.", cta: "تواصل مع المعلومات الطبية", blocks: [
      { title: "المحفظة الدوائية", body: "تتطور المنتجات الدوائية عبر تسعة مجالات علاجية وتُستخدم تحت الإرشاد الطبي. لذلك تُعرض وفق التصنيف العلاجي وبشكل معلوماتي غير ترويجي.", note: "القائمة حسب المجال العلاجي؛ اسم المنتج والشكل الدوائي فقط؛ ولا تُستخدم صور للمنتجات الدوائية." },
      { title: "المكملات والفيتامينات والعافية", body: "تضم محفظة صحة المستهلك فيتامينات ومعادن وتركيبات عافية للاحتياجات اليومية، من دعم المناعة إلى الدعم الغذائي وصحة المفاصل والعافية المعرفية وصحة الأسرة.", items: ["دعم المناعة", "أوميجا والعناصر الأساسية", "دعم المفاصل والحركة", "عافية الرجال", "عافية النساء", "دعم الحمل والأمومة", "تغذية الأطفال", "الدعم المعرفي والعصبي", "الفيتامينات والمعادن", "دعم الهضم"] },
      { title: "سنترفيتا", body: "سنترفيتا هي مجموعة كوباد المتخصصة من الفيتامينات والمعادن وتركيبات العافية، وتغطي احتياجات متنوعة من الدعم المعرفي والعصبي إلى عافية الرجال والنساء والتغذية قبل الولادة." },
      { title: "صحة الأطفال والأسرة", body: "صممت منتجات كوباد للأطفال والأسرة لدعم التغذية واحتياجات العافية اليومية عبر مراحل الحياة." },
    ] },
    "manufacturing-quality": { ...english.sections["manufacturing-quality"], eyebrow: "التصنيع والجودة", title: "التصنيع والجودة", intro: "تشكل عمليات التصنيع أساس محفظة كوباد الدوائية وصحة المستهلك، عبر الجمع بين منشآت الإنتاج المملوكة وقدرات التصنيع للغير لدعم العلامات والشراكات التجارية.", cta: "تواصل مع الشؤون التنظيمية", blocks: [
      { title: "تصنيع مبني للنمو", body: "تدعم عمليات كوباد محفظة متنامية من الأدوية والمكملات والتغذية، وتتيح للشركاء الاستفادة من القدرة الإنتاجية والخبرة الفنية عبر خدمات التصنيع للغير." },
      { title: "الجودة كمعيار تشغيلي", body: "يتطلب التصنيع الدوائي وصحة المستهلك نظم جودة دقيقة وتحكمًا في المستندات وانضباطًا تنظيميًا لكل فئة، وتعمل عمليات كوباد ضمن هذه المتطلبات باستمرار." },
      { title: "ضمن إطار منظم", body: "تعمل عمليات التصنيع وتطوير المنتجات والتواصل العام ضمن الأطر التنظيمية لهيئة الدواء المصرية وهيئة سلامة الغذاء ووزارة الصحة." },
    ] },
    insights: { ...english.sections.insights, eyebrow: "المعرفة والأخبار", title: "المعرفة والأخبار", intro: "تنشر كوباد محتوى تثقيفيًا عن الوعي بالأمراض والتغذية وتطورات الرعاية الصحية، مستقلًا عن التواصل الترويجي أو الخاص بالمنتجات.", cta: "عرض كل الموضوعات", blocks: [
      { title: "الوعي بالأمراض", body: "يتناول أساسيات المجالات العلاجية والحالات الصحية وإدارتها العامة وأهميتها للصحة العامة دون الإشارة إلى منتجات دوائية محددة.", items: ["فهم التهاب المفاصل الروماتويدي", "أساسيات صحة القلب والتمثيل الغذائي", "صحة الجهاز الهضمي", "التعرف على مشكلات صحة الجهاز التنفسي"] },
      { title: "التغذية والعافية", body: "يقدم تثقيفًا صحيًا عامًا عن الفيتامينات والمعادن ودعم العافية اليومي بما يتصل بمحفظة صحة المستهلك." },
      { title: "الشركة والقطاع", body: "يغطي تطورات كوباد ومحطات التصنيع والسياق الأوسع لصناعة الدواء في مصر." },
    ] },
    "partner-with-us": { ...english.sections["partner-with-us"], eyebrow: "شراكة معنا", title: "شراكة معنا", intro: "توفر قدرات كوباد التصنيعية واتساعها العلاجي ونمو صحة المستهلك أساسًا لشراكات تجارية منظمة في التوزيع والتصدير والتصنيع التعاقدي.", cta: "أرسل طلب شراكة", blocks: [
      { title: "شراكات التوزيع", body: "تعمل كوباد مع شركاء توزيع الصيدليات والرعاية الصحية في مصر لضمان الإتاحة المستمرة للمحفظة الدوائية وصحة المستهلك." },
      { title: "التعاون في التصدير", body: "تدعم الطاقة التصنيعية والمحفظة المتنامية فرص التصدير للأسواق الإقليمية، مع الانفتاح على مناقشات الشراكة." },
      { title: "التصنيع التعاقدي وللغير", body: "توفر كوباد للشركاء وصولًا إلى القدرة الإنتاجية والخبرة الفنية ونظم الجودة لتلبية احتياجات العلامات في السوق المصري." },
    ] },
    careers: { ...english.sections.careers, eyebrow: "الوظائف", title: "الوظائف", intro: "يتطلب نمو كوباد عبر الأدوية وصحة المستهلك والتصنيع فريقًا متعدد التخصصات يشمل المجالات العلمية والتشغيلية والتجارية والمؤسسية.", cta: "أرسل سيرتك الذاتية", blocks: [
      { title: "العمل في كوباد", body: "تمتد فرق كوباد بين التصنيع وضمان الجودة والشؤون التنظيمية والعمليات التجارية والوظائف المؤسسية، مع فرص تتوسع عبر الأعمال القائمة والناشئة." },
      { title: "الفرص الحالية", body: "تُعرض الوظائف المتاحة هنا، ويمكن للمهتمين تقديم طلباتهم لمراجعتها من فريق التوظيف في كوباد." },
    ] },
    contact: { ...english.sections.contact, eyebrow: "تواصل معنا", title: "تواصل معنا", intro: "يمكن توجيه الاستفسارات المؤسسية والتجارية والخاصة بالمنتجات عبر قنوات الاتصال المركزية في كوباد، لتصل إلى القسم المختص في الوقت المناسب.", cta: "أرسل استفسارك", blocks: [
      { title: "طرق التواصل", body: "يمكن تقديم الاستفسارات العامة وطلبات الشراكات والتوظيف والأسئلة المتعلقة بالمنتجات عبر التصنيفات المتاحة. ويوجّه المختصون إلى قناة المعلومات الطبية المخصصة.", items: ["استفسارات عامة", "الشراكات وتطوير الأعمال", "الوظائف", "استفسارات المنتجات", "المعلومات الطبية واليقظة الدوائية"] },
      { title: "المكتب المؤسسي", body: "تحتفظ كوباد فارما مصر بمكاتبها المؤسسية وعملياتها التصنيعية داخل مصر لدعم النشاط المحلي وشبكة الشراكات الإقليمية." },
    ] },
  },
};

export const siteCopy: Record<Locale, SiteCopy> = { en: english, ar: arabic };
