import type { Locale } from "@/lib/i18n";

const ui = {
  en: {
    home: { divisionsTitleLines: ["Four Divisions, One", "Corporate Structure"] },
    next: { next: "Next", enter: "Enter the next chapter", click: "Click to explore", destination: "Next destination", tap: "Tap to explore", hover: "Hover to open" },
    careers: { opportunities: "Current opportunities", view: "View position", kicker: "People power progress", disciplines: "Science · Operations · Commercial · Corporate", scroll: "Scroll to discover the paths" },
    therapy: { index: "Clinical index", portfolioMark: "COPAD / Clinical portfolio" },
    products: { navLabel: "Products page sections", overview: "Overview", portfolio: "Portfolio", spectrum: "Product spectrum / Four categories", formulations: "Formulations across the portfolio", journey: "Journey through the portfolio" },
    manufacturing: { navLabel: "Manufacturing and quality page sections", facility: "The Facility", system: "Operating System", insights: "Insights", next: "Next: knowledge", base: "Manufacturing base", assembly: "COPAD facility assembly", blueprint: "Blueprint to operation", stage: "Operating stage", flow: "Manufacturing flow", controlled: "Controlled flow", station: "Station" },
    insights: { library: "The COPAD Medical Library", journal: "COPAD Medical Journal", interactive: "Interactive COPAD medical issue", issueIndex: "Issue index", choose: "Choose your reading stream", editorial: "Editorial section", featured: "Featured reading", book: { header: "COPAD / INSIGHTS", company: "COPAD Pharma Egypt", companyFolio: "COPAD Pharma Egypt · 1989—2026", libraryFolio: "The COPAD Medical Library", valuesFolio: "Knowledge · Context · Responsibility", insightsFolio: "COPAD / Insights", issue: "Issue No. 01", title: "COPAD Insights", edition: "Healthcare knowledge, clearly considered", perspective: "Editorial perspective", purpose: "Credible knowledge, clearly communicated.", purposeBody: "Health and educational content designed to help readers understand the subject before anything else.", inside: "Inside this issue", ways: "Three ways into the story", streams: ["Disease Awareness", "Nutrition & Wellness", "Corporate & Industry"], lead: "Lead feature", feature: "From information to understanding", featureBody: "Medical context presented in an accessible and responsible way, without product promotion.", closing: "Closing note", close: "Read with perspective.", closeBody: "Every topic is a starting point for deeper understanding, not the end of the conversation.", back: "Knowledge, responsibly shared." } },
    partners: { navLabel: "Partnership page sections", overview: "Overview", areas: "Partnership Areas", kicker: "Growth starts with alignment", titleLines: ["Partner", "With Us"], spectrum: "Distribution · Export · Manufacturing", mark: "COPAD / PARTNERSHIPS", model: "Partnership model", explore: "Explore this route", modelsTitle: ["Three partnership models.", "One clear route."], modelsBody: "Choose the collaboration model that fits your opportunity, then share the right details through its dedicated inquiry form.", jump: "Jump to a partnership model", select: "Select", submit: "Submit partnership inquiry", sending: "Sending…", received: "Your inquiry has been sent successfully.", error: "We could not send your inquiry. Please try again.", fromAlignment: "From alignment to execution", steps: ["Define", "Validate", "Activate"], back: "Back to partnership areas", pathway: "The partnership pathway", pathwayTitle: "A clear route from alignment to execution", pathwayBody: "Every collaboration starts with a shared understanding, moves through readiness, and ends with a practical execution plan.", briefTitle: "Start with a clear brief of the opportunity", briefBody: "This form is tailored to this partnership route, so the right details reach the right team from the start." },
  },
  ar: {
    home: { divisionsTitleLines: ["أربعة قطاعات ضمن", "هيكل مؤسسي واحد"] },
    next: { next: "التالي", enter: "ادخل الفصل التالي", click: "اضغط للاستكشاف", destination: "الوجهة التالية", tap: "اضغط للاستكشاف", hover: "مرر لفتح البوابة" },
    careers: { opportunities: "الفرص الحالية", view: "عرض الوظيفة", kicker: "الموهبة تصنع التقدم", disciplines: "علم · تشغيل · تجارة · مؤسسات", scroll: "مرّر لاكتشاف المسارات" },
    therapy: { index: "الفهرس الإكلينيكي", portfolioMark: "كوباد / المحفظة الإكلينيكية" },
    products: { navLabel: "أقسام صفحة المنتجات", overview: "نظرة عامة", portfolio: "المحفظة", spectrum: "طيف المنتجات / أربع فئات", formulations: "تركيبة عبر المحفظة", journey: "رحلة داخل المحفظة" },
    manufacturing: { navLabel: "أقسام صفحة التصنيع والجودة", facility: "المصنع", system: "منظومة التشغيل", insights: "المعرفة", next: "المعرفة التالية", base: "قاعدة التصنيع", assembly: "تجميع منشأة كوباد", blueprint: "من المخطط إلى التشغيل", stage: "مرحلة تشغيل", flow: "مسار التشغيل", controlled: "تدفق منضبط", station: "محطة" },
    insights: { library: "مكتبة كوباد الطبية", journal: "مجلة كوباد الطبية", interactive: "عدد كوباد الطبي التفاعلي", issueIndex: "فهرس العدد", choose: "اختر مسار القراءة", editorial: "القسم التحريري", featured: "موضوعات مقترحة", book: { header: "كوباد / المعرفة", company: "كوباد فارما مصر", companyFolio: "كوباد فارما مصر · 1989—2026", libraryFolio: "مكتبة كوباد الطبية", valuesFolio: "معرفة · سياق · مسؤولية", insightsFolio: "كوباد / المعرفة والأخبار", issue: "الإصدار الأول", title: "رؤى كوباد", edition: "المعرفة الصحية بوضوح", perspective: "رؤيتنا التحريرية", purpose: "معرفة موثوقة، بلغة واضحة.", purposeBody: "محتوى صحي وتعليمي يساعد القارئ على فهم الموضوع قبل أي شيء آخر.", inside: "داخل هذا العدد", ways: "ثلاثة مسارات للقراءة", streams: ["الوعي بالأمراض", "التغذية والعافية", "الشركة والقطاع"], lead: "المقال الرئيسي", feature: "من المعلومة إلى الفهم", featureBody: "نقدّم السياق الطبي بصورة مبسطة ومسؤولة، بعيدًا عن الترويج للمنتجات.", closing: "كلمة أخيرة", close: "اقرأ بوعي.", closeBody: "كل موضوع بداية لفهم أعمق، وليس نهاية للحوار.", back: "معرفة مسؤولة." } },
    partners: { navLabel: "أقسام صفحة الشراكات", overview: "نظرة عامة", areas: "مجالات الشراكة", kicker: "نمو يبدأ من التوافق", titleLines: ["شراكة", "مع كوباد"], spectrum: "توزيع · تصدير · تصنيع", mark: "كوباد / شراكات", model: "نموذج شراكة", explore: "استكشف المسار", modelsTitle: ["ثلاثة نماذج للشراكة", "ومسار واضح لكل منها"], modelsBody: "اختر نموذج التعاون الأقرب لاحتياجك، ثم شارك فريقنا بالتفاصيل المطلوبة من خلال نموذج مخصص.", jump: "انتقل إلى نموذج الشراكة", select: "اختر", submit: "إرسال طلب الشراكة", sending: "جارٍ الإرسال…", received: "تم إرسال طلب الشراكة بنجاح.", error: "تعذر إرسال الطلب. يرجى المحاولة مرة أخرى.", fromAlignment: "من التوافق إلى التنفيذ", steps: ["تحديد المسار", "مراجعة الجاهزية", "بدء التنفيذ"], back: "العودة إلى مجالات الشراكة", pathway: "مسار العمل", pathwayTitle: "مسار واضح من التوافق إلى التنفيذ", pathwayBody: "كل شراكة تبدأ بفهم الاحتياج، ثم مراجعة الجاهزية، ثم وضع خطوات تنفيذ عملية وواضحة.", briefTitle: "لنبدأ بمعلومات واضحة عن الفرصة", briefBody: "هذا النموذج مصمم لهذا النوع من الشراكات حتى تصل التفاصيل الصحيحة مباشرة إلى الفريق المختص." },
  },
} as const;

export function getUiCopy(locale: Locale) {
  return ui[locale];
}
